import { Poppins } from 'next/font/google';

import { Providers } from './Providers';

import type { Metadata } from 'next';

import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '900'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={poppins.className}>{children}</body>
      </Providers>
    </html>
  );
}
